### ISSUE TITLE
Bot closing upon countdown

### ISSUE THREAD

**Issue by guwopg0d** [MrFums/ValorantBot#1]
I just tried the bot but whenever i filled in all the settings and its telling me to wait in the home screen, it shows on or two lines and then closes automatically. I have installed the latest python (3.9 i believe) and also ran the dependencies as admin.
i have not checked the installation of that but i think i saw some red lines when installing the last few dependencies, so that might be the issue..?
any tips for fixing this?
thanks :-)

**Comment by MrFums** [comment]
Yes the red lines is an error message when installing the dependency. I'm sure someone had this problem before and we solved it by uninstalling Python 3.9 and installing Python 3.8 and running the bat file again. Remember to add to PATH as well when installing.

**Comment by MrFums** [comment]
Assuming this is fixed now
