### ISSUE TITLE
Auto restart valorant

### ISSUE THREAD

**Issue by awiralesmana** [MrFums/ValorantBot#10]
When the game is found for deathmatch in 7-10 minutes, the bot will auto restart the game and wont  restart the bot (afk on game)

Know how to fix this ? 
Thankyou

**Comment by MrFums** [comment]
Not sure what you mean. Does valorant automatically restart when in a deathmatch game?

**Comment by awiralesmana** [comment]
This bug appear sometimes when the queue ended around 8++ minutes, like this
Game : queue 9:28 
Game : match found

Bot : restarting valorant, error issue 

The valorant is restarted but the bot wont restart itself

So it will be afk  in game and gained 0xp because the bot wont restart itself

I hope you know what i mean 
Please help mr Fums, thanks a lot

**Comment by awiralesmana** [comment]
[](https://youtu.be/ERXv3H2yaio)

Like this

**Comment by awiralesmana** [comment]
[the video](https://youtu.be/ERXv3H2yaio)

**Comment by Zuanvl** [comment]
try valbot ver 1.5.1 

https://github.com/MrFums/ValorantBot/releases/tag/1.5.1

**Comment by MrFums** [comment]
> try valbot ver 1.5.1
> 
> https://github.com/MrFums/ValorantBot/releases/tag/1.5.1

Yes, this should, within theory, fix your problem.

**Comment by awiralesmana** [comment]
Im using valbot v1.5.1 already 
Any idea ?

**Comment by MrFums** [comment]
Probably just increase the timer in the source code. Look for `future = time.now() + 900` (or something similar) in the game / inqueue(2) function.
