### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zuanvl** [MrFums/ValorantBot#12]
![image](https://user-images.githubusercontent.com/73916707/98052706-73e94980-1e69-11eb-9a65-a140e79c7d96.png)
when opening the bot I get an error like that

after selecting the banner the bot told me to wait for 10 seconds but the bots exits itself:(

im running windows 10 2004 version

**Comment by MrFums** [comment]
Nothing to do with my bot. Error with python installation and packages. Fresh install python
