### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by awiralesmana** [MrFums/ValorantBot#4]
Hello i have some prob, but
First, sorry for my bad english
Second, im so sorry i didnt have phyton etc skills 

I want to ask about "error 2 enter an interger" after the first game ended.
Can you tell me what should i do about this error ?

**Comment by MrFums** [comment]
After you have completed a game? so when you are on the end game screen?

**Comment by awiralesmana** [comment]
![image](https://user-images.githubusercontent.com/73724455/97765531-0bd2f480-1b45-11eb-9e57-ab7fea035095.jpeg)

Thanks for replying 
Yess, like this
I hope u can see it clearly

**Comment by MrFums** [comment]
When it asked you to select a banner before the bot started, what did you enter?

**Comment by awiralesmana** [comment]
I did enter "2" for valorant card

**Comment by MrFums** [comment]
Alright I think I know what the problem is. Going to push v1.5 in about 30 minutes after I check it and make sure it runs well. I'll leave a comment once it is out and try and download that and see if it works

**Comment by awiralesmana** [comment]
I appreciate your help. Thank you so much.

**Comment by MrFums** [comment]
Ok try the new version, sorry for the delay. Had a few bugs to fix. Please let me know if the error happens again. This issue is new so if it happens again I would guess that you need to install Python 3.8 and use that.

**Comment by awiralesmana** [comment]
Thank you so much. It work well

But there is some problem where the bot cant detect a match and afk in game because of that

**Comment by awiralesmana** [comment]
I already fix it 
I try to replace images "1.png" or the other one with my own match found screenshot
It work for a while, maybe. Ill comment if it dosnt work anymore
