### ISSUE TITLE
it doesn't play a new game can you help me pls:(

### ISSUE THREAD

**Issue by valoronat** [MrFums/ValorantBot#8]
Hi Mr.Fums, im using your bot but after 1 game, bot doesn't play a game by itself

**Comment by MrFums** [comment]
Need some more information, what does the bot console say, what part does it get up to, does it crash?

**Comment by valoronat** [comment]
Im stucking at waiting a game part :(

**Comment by MrFums** [comment]
Did you read the information in the bot? You have to read everything. What player card do you have equipped

**Comment by valoronat** [comment]
[-] Waiting for play button

 [√] Detected play button

 [-] Searching for deathmatch button

 [√] Detected deathmatch button

 [-] Waiting for menu

 [√] Detected at menu

 [-] Detecting if in queue

 [√] Detected in queue

 [-] Waiting for a game

 [√] Detected in game

 [-] Waiting for the game to end

i stucked there. Yes i equiped valorant card.

**Comment by MrFums** [comment]
Go through the images folder and make your own images. Make sure they have the same name
